# Logger options
log_iter: 100                 # How often to log the training loss
val_iter: 100                # How often to validate testing and save output images during training
description: 0.8_nr.5-3k
eval: false
# Optimization options
max_iter: 2000                 # Maximum number of training iterations
batch_size: 1                  # Batch size TODO: Minibatches S = (i, k) i: detector cell, k: view
loss: L2                       # Mean Squared Error
optimizer: Adam                # Optimizer for trainings
weight_decay: 0.0              # Weight decay
beta1: 0.9                     # Adam parameter
beta2: 0.999                   # Adam parameter
lr: 0.0001                     # Initial learning rate

# Model options
model: FFN                     # Feed Forward Network (Fully Connected Layers with ReLU activations and sigmoid output)
net:
  network_input_size: 512      # Input size for network
  network_output_size: 1
  network_depth: 8             # Depth of MLP layers
  network_width: 128           # Width of MLP layers

encoder:
  embedding: gauss             # Input embedding method fourier feautre mapping y(v) = [cos(2*pi*B*v), sin(2*pi*B*v)], B is sampled from Gaussian distribution N(0,sigma²)
  scale: 4                     # scale =standard deviation sigma
  embedding_size: 256          # Embedding size for input Fourier feature encoding # 128 in paper
  coordinates_size: 2

proj_size: 512                 # size of reconstructed projection matrix
num_proj_full_view: 512       # Number of projections of full view CT scan
num_proj_sparse_view: 128       # Number of projections for CT recon

slice_skip_threshold: 0.8     # threshold for reusing prior of sequential slices
accuracy_goal: 0.9             # threshold to end training early if accuracy is already high enough


down_sample_factor: 3          # [::3,::3,::3] -> [171,171,171]
#Data
#data: L067_FD_3_1.CT.0002.0090.2015.12.22.18.12.07.5968.358093561.IMA
#data: L096_FD_3_1.CT.0004.0130.2015.12.23.16.35.57.901651.360766576.IMA
data: rand_1024projs_7.h5
#data: rand_1024projs_fbp_volume_with_64_projections.hdf5
#data: 64_projections_volume.hdf5
img_size: 512    # (512, 512) grid size
num_slices: 512
#img_path: ./ner/data/ct_data/L067_FD_3_1.CT.0002.0090.2015.12.22.18.12.07.5968.358093561.IMA  # Image path for data loading
#img_path: '../../lgrp/edu-2024-1-bsc-buchfiml/rand_1024projs_fbp_volume_with_64_projections.hdf5'
img_path: '../../lgrp/edu-2024-1-bsc-buchfiml/shapes_sparse_view/rand_1024projs_7.h5'
