# Logger options
log_iter: 100                  # How often to log the training loss
val_iter: 100                  # How often to validate testing and save output images during training
description:
# Optimization options
max_iter: 5100                 # Maximum number of training iterations
batch_size: 1                  # Batch size TODO: Minibatches S = (i, k) i: detector cell, k: view
loss: L2                       # Mean Squared Error
optimizer: Adam                # Optimizer for trainings
weight_decay: 0.0              # Weight decay
beta1: 0.9                     # Adam parameter
beta2: 0.999                   # Adam parameter
lr: 0.0001                     # Initial learning rate

# Model options
model: FFN                     # Feed Forward Network (Fully Connected Layers with ReLU activations and sigmoid output)
net:
  network_input_size: 512      # Input size for network
  network_output_size: 1
  network_depth: 8             # Depth of MLP layers
  network_width: 128           # Width of MLP layers

encoder:
  embedding: gauss             # Input embedding method fourier feautre mapping y(v) = [cos(2*pi*B*v), sin(2*pi*B*v)], B is sampled from Gaussian distribution N(0,sigma²)
  scale: 3                     # scale =standard deviation sigma
  embedding_size: 256          # Embedding size for input Fourier feature encoding # 128 in paper
  coordinates_size: 3

num_proj_full_view: 1024       # Number of projections of full view CT scan
num_proj_sparse_view: 64       # Number of projections for CT recon

down_sample_factor: 3          # [::3,::3,::3] -> [171,171,171]

#Data
data: volume_GT_1200Proj.hdf5
#data: rand_1024projs_7.h5
#data: volume.hdf5
img_path: '../../lgrp/edu-2024-1-bsc-buchfiml/AmmarResults/volume_GT_1200Proj.hdf5'
#img_path: '../../lgrp/edu-2024-1-bsc-buchfiml/shapes_sparse_view/rand_1024projs_7.h5'
#img_path: '../../lgrp/edu-2024-1-bsc-buchfiml/AmmarResults/CylinderHeadLong/volume.hdf5'

cb_para:
  num_projs: 64
  pixelSize: 0.126994
  voxelSize: 0.06400318
  SDD:  1281.909
  SOD: 646.0335
  ObjectOffsetX: 0
  ObjectRoll: 0
  projectionzshift_pixel: 0
  InitialAngle: 0

cb_para_full:
  num_projs: 512
  pixelSize: 0.126994
  voxelSize: 0.06400318
  SDD:  1281.909
  SOD: 646.0335
  ObjectOffsetX: 0
  ObjectRoll: 0
  projectionzshift_pixel: 0
  InitialAngle: 0